/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConocenosHistoriaRouteImport } from './routes/conocenos.historia'
import { Route as ConocenosCulturaRouteImport } from './routes/conocenos.cultura'

const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConocenosHistoriaRoute = ConocenosHistoriaRouteImport.update({
  id: '/conocenos/historia',
  path: '/conocenos/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const ConocenosCulturaRoute = ConocenosCulturaRouteImport.update({
  id: '/conocenos/cultura',
  path: '/conocenos/cultura',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/nosotros': typeof NosotrosRoute
  '/conocenos/cultura': typeof ConocenosCulturaRoute
  '/conocenos/historia': typeof ConocenosHistoriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/nosotros': typeof NosotrosRoute
  '/conocenos/cultura': typeof ConocenosCulturaRoute
  '/conocenos/historia': typeof ConocenosHistoriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/nosotros': typeof NosotrosRoute
  '/conocenos/cultura': typeof ConocenosCulturaRoute
  '/conocenos/historia': typeof ConocenosHistoriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/nosotros'
    | '/conocenos/cultura'
    | '/conocenos/historia'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/home' | '/nosotros' | '/conocenos/cultura' | '/conocenos/historia'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/nosotros'
    | '/conocenos/cultura'
    | '/conocenos/historia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  NosotrosRoute: typeof NosotrosRoute
  ConocenosCulturaRoute: typeof ConocenosCulturaRoute
  ConocenosHistoriaRoute: typeof ConocenosHistoriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conocenos/historia': {
      id: '/conocenos/historia'
      path: '/conocenos/historia'
      fullPath: '/conocenos/historia'
      preLoaderRoute: typeof ConocenosHistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conocenos/cultura': {
      id: '/conocenos/cultura'
      path: '/conocenos/cultura'
      fullPath: '/conocenos/cultura'
      preLoaderRoute: typeof ConocenosCulturaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  NosotrosRoute: NosotrosRoute,
  ConocenosCulturaRoute: ConocenosCulturaRoute,
  ConocenosHistoriaRoute: ConocenosHistoriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
