/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Nuestra_trayectoriaRouteImport } from './routes/nuestra_trayectoria'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as LocationRouteImport } from './routes/location'
import { Route as HomeRouteImport } from './routes/home'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConocenosHistoriaRouteImport } from './routes/conocenos.historia'
import { Route as ConocenosCulturaRouteImport } from './routes/conocenos.cultura'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const Nuestra_trayectoriaRoute = Nuestra_trayectoriaRouteImport.update({
  id: '/nuestra_trayectoria',
  path: '/nuestra_trayectoria',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConocenosHistoriaRoute = ConocenosHistoriaRouteImport.update({
  id: '/conocenos/historia',
  path: '/conocenos/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const ConocenosCulturaRoute = ConocenosCulturaRouteImport.update({
  id: '/conocenos/cultura',
  path: '/conocenos/cultura',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRoute
  '/home': typeof HomeRoute
  '/location': typeof LocationRoute
  '/nosotros': typeof NosotrosRoute
  '/nuestra_trayectoria': typeof Nuestra_trayectoriaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/conocenos/cultura': typeof ConocenosCulturaRoute
  '/conocenos/historia': typeof ConocenosHistoriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRoute
  '/home': typeof HomeRoute
  '/location': typeof LocationRoute
  '/nosotros': typeof NosotrosRoute
  '/nuestra_trayectoria': typeof Nuestra_trayectoriaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/conocenos/cultura': typeof ConocenosCulturaRoute
  '/conocenos/historia': typeof ConocenosHistoriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blogs': typeof BlogsRoute
  '/home': typeof HomeRoute
  '/location': typeof LocationRoute
  '/nosotros': typeof NosotrosRoute
  '/nuestra_trayectoria': typeof Nuestra_trayectoriaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/conocenos/cultura': typeof ConocenosCulturaRoute
  '/conocenos/historia': typeof ConocenosHistoriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blogs'
    | '/home'
    | '/location'
    | '/nosotros'
    | '/nuestra_trayectoria'
    | '/blog/$slug'
    | '/conocenos/cultura'
    | '/conocenos/historia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blogs'
    | '/home'
    | '/location'
    | '/nosotros'
    | '/nuestra_trayectoria'
    | '/blog/$slug'
    | '/conocenos/cultura'
    | '/conocenos/historia'
  id:
    | '__root__'
    | '/'
    | '/blogs'
    | '/home'
    | '/location'
    | '/nosotros'
    | '/nuestra_trayectoria'
    | '/blog/$slug'
    | '/conocenos/cultura'
    | '/conocenos/historia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogsRoute: typeof BlogsRoute
  HomeRoute: typeof HomeRoute
  LocationRoute: typeof LocationRoute
  NosotrosRoute: typeof NosotrosRoute
  Nuestra_trayectoriaRoute: typeof Nuestra_trayectoriaRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ConocenosCulturaRoute: typeof ConocenosCulturaRoute
  ConocenosHistoriaRoute: typeof ConocenosHistoriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nuestra_trayectoria': {
      id: '/nuestra_trayectoria'
      path: '/nuestra_trayectoria'
      fullPath: '/nuestra_trayectoria'
      preLoaderRoute: typeof Nuestra_trayectoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conocenos/historia': {
      id: '/conocenos/historia'
      path: '/conocenos/historia'
      fullPath: '/conocenos/historia'
      preLoaderRoute: typeof ConocenosHistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conocenos/cultura': {
      id: '/conocenos/cultura'
      path: '/conocenos/cultura'
      fullPath: '/conocenos/cultura'
      preLoaderRoute: typeof ConocenosCulturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogsRoute: BlogsRoute,
  HomeRoute: HomeRoute,
  LocationRoute: LocationRoute,
  NosotrosRoute: NosotrosRoute,
  Nuestra_trayectoriaRoute: Nuestra_trayectoriaRoute,
  BlogSlugRoute: BlogSlugRoute,
  ConocenosCulturaRoute: ConocenosCulturaRoute,
  ConocenosHistoriaRoute: ConocenosHistoriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
